version: "3"

services:
  backend:
    image: musia/gigitise-backend
    build:
      context: ./client-backend
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
